Grid usage
kruton-development/grand-theft-transport pull request #19
Opened 2021-03-02 19:11 UTC by wohajo

2021-03-02 21:56 UTC, dzkb requested changes

2021-03-02 21:56 UTC, dzkb commented on gtt-jobs/ui/dist/main.css
> +/*
I believe this file should not be tracked on git.

2021-03-02 21:56 UTC, dzkb commented on gtt-jobs/ui/dist/main.js
> +const L = window["L"];
I believe this file should not be tracked as well. Both are transpiled distributables.

2021-03-02 21:56 UTC, dzkb commented on gtt-jobs/ui/index.html
> +<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
In the future we'll have to provide all the dependencies locally. In MTA we cannot reliably request for external assets - for each new domain we'd have to ask the player for permission to make a request.

2021-03-02 21:56 UTC, dzkb commented on gtt-jobs/ui/_sass/main.scss
> +        font-size: x-large;
I see you're using media query for managing font size. Is there any option to make the font size relative to the view, like using viewport units + media query (to maintain a minimal font-size for text to be readable)?

2021-03-03 15:12 UTC, wohajo commented on gtt-jobs/ui/dist/main.js
> +const L = window["L"];
I am sorry, I misunderstood previous request. This is now fixed and untracked.

2021-03-03 15:13 UTC, wohajo commented on gtt-jobs/ui/index.html
> +<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
Working on importing leaflet to JS from NPM.

2021-03-03 15:13 UTC, wohajo commented on gtt-jobs/ui/_sass/main.scss
> +        font-size: x-large;
I changed font size to be related to viewport - needs to be reviewed.

2021-03-03 15:36 UTC, dzkb approved these changes

2021-03-03 15:36 UTC, merged